# Generated by Django 4.2 on 2025-05-25 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='itemdesc',
            new_name='item_desc',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='itemname',
            new_name='item_name',
        ),
    ]
